### ISSUE TITLE
chore: Research on a simple, yet powerful way to put a RAG application together

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/tutorials#11]
## Overview

Module 3 involves creating an application with all the various components of RAG. This is more of the frontend or api usage for the users that will be using this system. We need to figure out what would be the easiest way to get started. Some thoughts may be a CLI application with [typer](https://typer.tiangolo.com/) or web app with [streamlit](https://streamlit.io/).

**Comment by anantmittal** [comment]
[LlamaIndex](https://docs.llamaindex.ai/en/stable/) is another option.

**Comment by lsetiawan** [comment]
> [LlamaIndex](https://docs.llamaindex.ai/en/stable/) is another option.

After looking into it, this looks like the competing LLM framework to langchain rather a deployment frontend framework.

**Comment by lsetiawan** [comment]
Another potential of deployment integration is the JupterAI as I mentioned in Slack: https://jupyter-ai.readthedocs.io/en/latest/users/index.html#learning-about-local-data

**Comment by lsetiawan** [comment]
After some thought and conversation with @vanitech. We've decided that for simplicity let's go with a command line application for the tutorial.. which in this case, let's use https://typer.tiangolo.com/
