### ISSUE TITLE
feat: Create tutorial notebook from prototype

### ISSUE THREAD

**Issue by vanitech** [uw-ssec/tutorials#17]
@lsetiawan has created a prototype for Module 2 of the scipy tutorial at https://gist.github.com/lsetiawan/ed5d45f037970515e75db0add987a1aa

Using this as a starting point, create the tutorial and write clear descriptions for each step. 
Ensure coverage for the tasks outlined under the Module 2 description at https://github.com/uw-ssec/tutorials/tree/main/SciPy2024

**Comment by atambay37** [comment]
Here are the individual issues for each of the Module 2 Elements: #41 , #42 , #43, #44, #45, #46, #47, #48
