### ISSUE TITLE
feat: Create Embedding Tutorial 

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/tutorials#19]
## Overview

After @anujsinha3 have done such a thorough investigation on embedding models on issue #6, we need to put together a comprehensive tutorial on this.

### Outline

- What are embeddings?
- Importance of embeddings in RAG applications
- How to choose the right open-source embedding model for your RAG application.
- Evaluating embedding models: what to look out for? performance considerations?

**Comment by lsetiawan** [comment]
Example tutorial by MongoDB: https://www.mongodb.com/developer/products/atlas/choose-embedding-model-rag/#measuring-retrieval-quality

**Comment by atambay37** [comment]
#45

**Comment by lsetiawan** [comment]
Completed in https://github.com/uw-ssec/tutorials/pull/34
