### ISSUE TITLE
feat: Incorporate astro questions into the tutorial

### ISSUE THREAD

**Issue by vanitech** [uw-ssec/tutorials#20]
Questions to ask
 
•	What observations show evidence for dark matter
•	What are the most popular theories for what dark matter might be made of
•	Does dark matter need to be a particle
•	What is the expected mass of dark matter
•	What experiments are currently ongoing and searching for dark matter 
•	How do they work
•	What type of dark matter would the LHC be able to detect
•	Can you modify gravity to explain dark matter. If so how
 
•	How do astronomers detect the presence of planets around nearby stars
•	What is an eclipsing binary star
•	Can you describe a taxonomy for different classes of variable stars
•	What would the light curve of a tidal disruption event look like. How would it be different from a super nova
•	How do supernova explode
•	How is a Type II SN different from a Type 1a

TODO: define evaluation criteria

**Comment by lsetiawan** [comment]
@IshikaKhandelwal has integrated these questions in #9, updates will be posted soon.

**Comment by IshikaKhandelwal** [comment]
Response from` OLMO model `using `transformers` only for all the above prompts as well as the 2 sample prompts from AstroLLama chat: https://uwnetid-my.sharepoint.com/:w:/g/personal/ishikha_uw_edu/ES3avnpFeRNOuvD-7XIisaEBOSSvpiFZs0zC0zqBcgLZfw?e=pynXf5

Code for the model: https://colab.research.google.com/drive/15F3XAhthvLC0fZfWZjPXhc0NL_5yKjSr?usp=sharing

**Comment by vanitech** [comment]
Added questions in a single file and retrieved context 
[context.txt](https://github.com/uw-ssec/tutorials/files/15005520/context.txt)
[statementfile.txt](https://github.com/uw-ssec/tutorials/files/15005523/statementfile.txt)
