### ISSUE TITLE
feat: Tutorial Module 1: Overview

### ISSUE THREAD

**Issue by atambay37** [uw-ssec/tutorials#35]

**Comment by anantmittal** [comment]
This part can be a brief and quick outline of the entire tutorial:
1. Basics of language models and code to implement a small language model
2. LLMs and ways to interact with them, i.e., through prompt engineering
3. Open source LLMs and why OLMo
4. 2-3 lines about LangChain or genAI application frameworks
5. Pitfalls of LLMs (hallucinations, etc.)
6. Ways to make them better (we can say there are multiple techniques, but we will focus on RAG)
7. Make LLMs work with your data
8. Publishing / Deploying your app

**Comment by anantmittal** [comment]
@lsetiawan: Should this be a PowerPoint slide? Or should we explore https://rise.readthedocs.io/en/latest/?

**Comment by vanitech** [comment]
This should have the agenda with time for each module and task. Explanations / theory needs to be kept very brief.

**Comment by vanitech** [comment]
Addressed mostly in https://github.com/uw-ssec/tutorials/blob/main/SciPy2024/module1/llms-and-prompt-engineering-with-olmo.ipynb and this is generic information with lot of resources available outside the tutorial.
