### ISSUE TITLE
feat: Tutorial Module 1: LLMs and Prompt Engineering

### ISSUE THREAD

**Issue by atambay37** [uw-ssec/tutorials#37]

**Comment by anantmittal** [comment]
* Intro to LLMs: a large amount of data (almost the entire internet), attention-based architecture, transformers, needs a lot of computing, requires millions of $, and not everyone can train them. 
* One way to interact with LLMs is prompts
* Common LLM parameters: temperature, top-k, etc.
* Prompting Techniques: Zero-shot, few-shot, and maybe another technique like chain-of-thought or ReAct with OLMo

**Comment by anantmittal** [comment]
> * Intro to LLMs: a large amount of data (almost the entire internet), attention-based architecture, transformers, needs a lot of computing, requires millions of $, and not everyone can train them.
> 
>     * One way to interact with LLMs is prompts
> 
>     * Common LLM parameters: temperature, top-k, etc.
> 
>     * Prompting Techniques: Zero-shot, few-shot, and maybe another technique like chain-of-thought or ReAct with OLMo

According to our [original plan](https://uw-ssec-tutorials.readthedocs.io/en/latest/SciPy2024/README.html), #39 comes after this module, but I think #39 can overlap with LLM parameters / prompting techniques section in this module.

**Comment by vanitech** [comment]
https://github.com/uw-ssec/tutorials/blob/main/SciPy2024/module1/llms-and-prompt-engineering-with-olmo.ipynb
