### ISSUE TITLE
feat: Tutorial Module 1: Python Environment Setup

### ISSUE THREAD

**Issue by atambay37** [uw-ssec/tutorials#38]

**Comment by anantmittal** [comment]
@lsetiawan: I'm not sure what this module will contain. If my understanding is correct, the environment setup should happen before module 1 starts, right?

**Comment by vanitech** [comment]
The instructions need to be listed out. Recommend a scaled down version of https://github.com/uw-ssec/rse-guidelines/blob/main/fundamentals/code-environment.md

**Comment by vanitech** [comment]
Available at https://uw-ssec-tutorials.readthedocs.io/en/latest/SciPy2024/module1/setup.html
