### ISSUE TITLE
feat: Tutorial Module 1: LLM-Powered Application Framework (LangChain)

### ISSUE THREAD

**Issue by atambay37** [uw-ssec/tutorials#40]

**Comment by anantmittal** [comment]
We obviously can't explain the entire LangChain package. So maybe we can talk about things that we plan to use in Module 2:
* Chaining
* Data Loaders
* Other abstractions LangChain provides for embeddings, etc.

We should probably avoid delving into words we haven't explained yet. For example, LangChain provides abstractions for multiple vector stores and embeddings, but we cover that in Module 2.

**Comment by anantmittal** [comment]
From discussion with @IshikaKhandelwal, @anujsinha3:
Maybe focus on `Why LangChain?,` and `Chaining,` and keep other LangChain abstractions for Module 2.

**Comment by vanitech** [comment]
Addressed in https://github.com/uw-ssec/tutorials/blob/main/SciPy2024/module1/langchain.ipynb
