### ISSUE TITLE
feat: Tutorial Module 2: Data Loading

### ISSUE THREAD

**Issue by atambay37** [uw-ssec/tutorials#45]
(e.g., GitHub repositories, research manuscripts, software documentation, etc.), Chunking, and Embedding

**Comment by vanitech** [comment]
Missing github, everything else is available at https://uw-ssec-tutorials.readthedocs.io/en/latest/SciPy2024/appendix/langchain-document-loaders.html

**Comment by anantmittal** [comment]
We didn't use [LangChain's GitHub loaders](https://python.langchain.com/v0.2/docs/integrations/document_loaders/github/) for Astropy documentation. 

The [qdrant notebook](https://uw-ssec-tutorials.readthedocs.io/en/latest/SciPy2024/appendix/qdrant-vector-database-creation.html) in the Appendix has the code that we used.
