### ISSUE TITLE
feat: Tutorial Module 3: Try with your data!

### ISSUE THREAD

**Issue by atambay37** [uw-ssec/tutorials#51]
Yesterday after eScience team meeting, it was brought up that we currently do not have any guidelines for participants that wants to bring their own data. This involves how much data can they bring and play with locally or in codespaces.

**Comment by anantmittal** [comment]
I wonder if this can be a `fill in the blanks` notebook with the following sections:
1. Import all the relevant packages 
-- langchain, qdrant, our own ssec_tutorials module, etc.
2. Load OLMo
3. Data Setup 
-- use code from Appendix notebooks to index your data using qdrant or [upload your files to Codespace](https://stackoverflow.com/questions/62284623/how-can-i-upload-a-file-to-a-github-codespaces-environment) in `resources/data` folder
4. QnA Pipeline with RAG
-- either using qdrant or using the uploaded files to get relevant context
