### ISSUE TITLE
chore: Research on the best embedding models for the tutorial

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/tutorials#6]
## Overview

There are so many embedding models as seen here: https://huggingface.co/sentence-transformers. This piece is critical on creating the best vector, which then gets feed into the VectorDB. Figuring out the most optimized embedding model is key here and probably having a good knowledge will be beneficial for participants, so let's look into it. @vanitech and @anantmittal do you have any insights on this?

## Resources

- https://huggingface.co/blog/getting-started-with-embeddings
- https://github.com/reichenbch/RAG-examples/tree/main

**Comment by anantmittal** [comment]
This [article](https://thenewstack.io/the-building-blocks-of-llms-vectors-tokens-and-embeddings/) explains the idea quite well.

**Comment by lsetiawan** [comment]
This is great @anantmittal! Thanks for sharing, I think we should explain this concept during the tutorial session well to really clear up the terms and concepts.

**Comment by lsetiawan** [comment]
Found this really great resource on comparisons of embeddings: https://medium.com/@nils_reimers/openai-gpt-3-text-embeddings-really-a-new-state-of-the-art-in-dense-text-embeddings-6571fe3ec9d9

**Comment by vanitech** [comment]
Huggingface MTEB leaderboard is a good resource for this 
https://huggingface.co/spaces/mteb/leaderboard

**Comment by anujsinha3** [comment]
Found this great article on choosing embedding models based on use-case.
https://www.rungalileo.io/blog/mastering-rag-how-to-select-an-embedding-model

If TLDR, read the following sections:

- Sparse Embedding
- Long Context Embedding
- Code Embedding
- Choosing the Right Embedding Model

**Comment by anujsinha3** [comment]
Comparative Empirical Analysis for 6 Embedding Models:
https://docs.google.com/spreadsheets/d/1Vd1M15MiA5DbSJrrCAkFHMpT10CjWT5mLyFdhsuHNdM/edit#gid=0
