### ISSUE TITLE
chore: Verify Python Environment Setup

### ISSUE THREAD

**Issue by anantmittal** [uw-ssec/tutorials#69]
https://uw-ssec-tutorials.readthedocs.io/en/latest/SciPy2024/module1/setup.html

**Comment by anantmittal** [comment]
[Using a Conda Environment](https://uw-ssec-tutorials.readthedocs.io/en/latest/SciPy2024/module1/setup.html#using-a-conda-environment):
* No errors in module 1 notebooks

**Comment by anantmittal** [comment]
[Using Codespaces:](https://uw-ssec-tutorials.readthedocs.io/en/latest/SciPy2024/module1/setup.html#using-github-codespaces)
* No errors in module 1 notebooks

**Comment by lsetiawan** [comment]
Woo hoo! Sounds great. Thanks!
