### ISSUE TITLE
chore: Verify Astropy GitHub Fetch Method uses GitHub Personal Access token

### ISSUE THREAD

**Issue by anantmittal** [uw-ssec/tutorials#74]

**Comment by IshikaKhandelwal** [comment]
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

Fetching Astropy does not require using personal access token, since it is a public repo and can be fetched unauthorised.

**Comment by anantmittal** [comment]
Fix:
> response = requests.get(github_file_url, headers={ 'Accept': 'application/vnd.github.v3.raw', 'Authorization': f'token {ACCESS_TOKEN}' })
