### ISSUE TITLE
feat: Create tutorial on parsing arXiv dataset

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/tutorials#8]
## Overview

@vanitech presented a really great dataset that would be really beneficial to be inserted into the vector database for use as context for the RAG approach. This dataset is essentially all of the papers in arXiv: https://www.kaggle.com/datasets/Cornell-University/arxiv/data

After some investigation it looks like this data lives in Google Cloud Storage, so it can easily be retrieved with `fsspec` without any credentials!

The kaggle repository does contain an index of this data, we can either just grab the data from gcs or directly from arXiv using langchain arXiv loader: https://python.langchain.com/docs/integrations/document_loaders/arxiv

**Comment by lsetiawan** [comment]
This is currently being done in #24

**Comment by atambay37** [comment]
https://github.com/uw-ssec/tutorials/commit/d86cc689129294d61ee5b52cf294fb56e9cf14a9

**Comment by vanitech** [comment]
Completed at https://uw-ssec-tutorials.readthedocs.io/en/latest/SciPy2024/appendix/astrophysics-dataset-creation.html
